### ISSUE TITLE
SynthDerm dataset

### ISSUE THREAD

**Issue by gabriele-dominici** [asmadotgh/dissect#1]
Hi, I am interested in testing a new approach on the SynthDerm dataset, but it seems that it is not available anymore. Am I wrong? Is it possible to have a new source to find the dataset?

Thank you very much in advance

**Comment by craigsonoffergus** [comment]
Thanks for bringing this up! The new link for the dataset is https://mitmedialabaffectivecomputing.github.io/SynthDermDataset/

We'll get the README updated to point to that link as soon as possible.

**Comment by gabriele-dominici** [comment]
Thank you so much for the answer. 

I have also another question: are there also available labels for the concepts used to generate the images (colors, size, ecc.)? I haven't found them yet. 
Is there an automatic way to extract them from the images? 

Thank you so much again

**Comment by asmadotgh** [comment]
Hi, thank you for your interest in this dataset. Since the data has been generated systematically with nested loops in the following order, you can use this logic to infer the metadata:

First 6 x 3 x 3 x 5 x 5= 1350 examples, include benign cases:

> LEN_FP_SKIN_TONE: [I, ..., VI] referring to the Fitzpatrick scale
> LEN_RND_SKIN_TONE: [1,2,3] referring to slightly darker, base, slightly lighter color variants, respectively.
> LEN_RND_SIZE: [1,2,3] referring to smaller, base, slightly larger variants, respectively.
> LEN_RND_X_OFFSET: [1,..,5] slightly moving the lesion from left to right, respectively.
> LEN_RND_Y_OFFSET: [1,..,5] slightly moving the lesion from top to bottom, respectively.

Next 3 x 2 x 6 x 28 = 1008 examples, include malignant cases of types A/B/C:

> lesion_type : [1,..,3] (1: A- asymmetrical, 2: B- Jagged Border , 3: C- Different colors)
> Surgical marking: [0, 1] (0: no marking, 1: surgical marking)
> LEN_FP_SKIN_TONE: [I, ..., VI]
> 28 samples with random values for (skin_tone_additive_noise, size, x_offset, y_offset)

Next 2 x 6 x 3 x 3 x 3 = 324 examples include malignant cases of type D:

> Surgical marking: [0, 1] (0: no marking, 1: surgical marking)
> LEN_FP_SKIN_TONE: [I, ..., VI]
> LEN_RND_SKIN_TONE: [1,2,3]
> LEN_RND_X_OFFSET: [1,2,3] - note that since these lesions are larger, only 3 horizontal offsets are used here.
> LEN_RND_Y_OFFSET: [1,2,3] - note that since these lesions are larger, only 3 vertical offsets are used here.


For example, metadata for the following would be: 
0000001.jpg:

> Shape: normal
> Fitzpatrick scale of skin tone: I
> Color variation: 1
> Size variation: 1
> X offset: 1
> Y offset: 1

0002682.jpg

> Shape: Large diameter
> Has surgical marking: Yes
> Fitzpatrick scale of skin tone: VI
> Color variation: 3
> X offset: 3
> Y offset: 3
